name: setup-ndk

description: Setup NDK for lyra build

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;21.4.7075529"
